[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "cd apps/api",
  "pnpm db:generate",
  "pnpm build"
]

[start]
cmd = "cd apps/api && node dist/index.js"
